# Generated by Django 3.2.4 on 2021-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
